const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.join(__dirname, '..');
const configPath = path.join(rootDir, 'public', 'games-config.js');
const dbPath = path.join(rootDir, 'src', 'db.js');
const serverPath = path.join(rootDir, 'src', 'server.js');
const htmlPath = path.join(rootDir, 'public', 'nchat', 'index.html');
const cssPath = path.join(rootDir, 'public', 'nchat', 'style.css');
const jsPath = path.join(rootDir, 'public', 'nchat', 'script.js');

test('nchat is wired as a standalone Nexa-only app route', () => {
  const config = fs.readFileSync(configPath, 'utf8');
  const db = fs.readFileSync(dbPath, 'utf8');
  const server = fs.readFileSync(serverPath, 'utf8');

  assert.match(config, /slug:\s*'nchat'/);
  assert.match(config, /name:\s*'Nchat'/);
  assert.match(config, /route:\s*'\/nchat\/'/);
  assert.match(config, /showInGamesHub:\s*0/);
  assert.match(db, /slug:\s*'nchat'/);
  assert.match(server, /'nchat':\s*'\/nchat\/'/);
  assert.match(server, /app\.post\('\/api\/nchat\/session'[\s\S]*\.\.\.buildNchatBootstrapPayload\(session\)/);
  assert.match(server, /app\.get\('\/api\/nchat\/events'[\s\S]*res\.setHeader\('Cache-Control', 'no-store, no-cache, no-transform, must-revalidate, proxy-revalidate'\)/);
  assert.match(server, /res\.write\('event: nchat\.conversation-updated\\ndata: \{"bootstrap":true\}\\n\\n'\);[\s\S]*if \(typeof res\.flush === 'function'\) res\.flush\(\);/);
});

test('nchat html includes app shell, tabs, and profile setup hooks', () => {
  assert.equal(fs.existsSync(htmlPath), true);
  const html = fs.readFileSync(htmlPath, 'utf8');

  assert.match(html, /<title>Claw800 Nchat<\/title>/);
  assert.match(html, /data-nchat-app/);
  assert.match(html, /id="nchatGuard"/);
  assert.match(html, /id="nchatChatPanel"/);
  assert.match(html, /id="nchatMePanel"/);
  assert.match(html, /data-tab-target="chat"/);
  assert.match(html, /data-tab-target="me"/);
  assert.match(html, /id="nchatSearchInput"/);
  assert.match(html, /id="nchatConversationList"/);
  assert.match(html, /id="nchatSearchResults"/);
  assert.match(html, /id="nchatConversationView"/);
  assert.doesNotMatch(html, /id="nchatStatus"/);
  assert.doesNotMatch(html, /class="nchat-header"/);
  assert.match(html, /id="nchatMessageList"/);
  assert.match(html, /id="nchatComposerInput"/);
  assert.match(html, /id="nchatProfileSetupModal"/);
  assert.match(html, /id="nchatProfileClose"/);
  assert.match(html, /id="nchatProfileClose"[^>]*>关闭<\/button>/);
  assert.match(html, /id="nchatProfileAvatarInput"/);
  assert.match(html, /id="nchatProfileNicknameInput"/);
  assert.match(html, /id="nchatProfileFeedback"/);
  assert.match(html, /id="nchatMyAvatar"/);
  assert.match(html, /id="nchatMyNickname"/);
  assert.match(html, /id="nchatMyChatId"/);
  assert.match(html, /id="nchatProfileEditButton"/);
  assert.match(html, /id="nchatProfileEditButton"[^>]*>编辑<\/button>/);
  assert.doesNotMatch(html, />编辑资料<\/button>/);
  assert.match(html, /id="nchatProfileAvatarPreview"/);
  assert.match(html, /\/nchat\/style\.css\?v=20260418-01/);
  assert.match(html, /\/nchat\/script\.js\?v=20260418-01/);
});

test('nchat css defines mobile app shell, bottom nav, unread badge, and conversation layout', () => {
  assert.equal(fs.existsSync(cssPath), true);
  const css = fs.readFileSync(cssPath, 'utf8');

  assert.match(css, /--nchat-accent:/);
  assert.match(css, /\.nchat-app\s*\{/);
  assert.match(css, /\.nchat-app \[hidden\]\s*\{[\s\S]*display:\s*none !important;/);
  assert.match(css, /\.nchat-panel\s*\{/);
  assert.match(css, /\.nchat-profile-card__actions\s*\{/);
  assert.match(css, /\.nchat-profile-feedback\s*\{/);
  assert.match(css, /\.nchat-profile-preview\s*\{/);
  assert.match(css, /\.nchat-modal__actions\s*\{/);
  assert.match(css, /\.nchat-modal__close\s*\{/);
  assert.match(css, /\.nchat-nav\s*\{/);
  assert.match(css, /\.nchat-message-block__time\s*\{/);
  assert.match(css, /\.nchat-nav__item\.is-active/);
  assert.match(css, /\.nchat-conversation-list\s*\{/);
  assert.match(css, /\.nchat-conversation-row\s*\{[\s\S]*text-align: left;/);
  assert.match(css, /\.nchat-conversation-row__main\s*\{[\s\S]*text-align: left;/);
  assert.match(css, /\.nchat-unread-badge\s*\{/);
  assert.match(css, /\.nchat-message\.is-pending\s*\{/);
  assert.match(css, /\.nchat-modal\[hidden\]\s*\{[\s\S]*display:\s*none;/);
  assert.match(css, /@media \(max-width:\s*720px\)/);
});

test('nchat script includes nexaauth, session/bootstrap/search/message, and realtime hooks', () => {
  assert.equal(fs.existsSync(jsPath), true);
  const js = fs.readFileSync(jsPath, 'utf8');

  assert.match(js, /const NEXA_PROTOCOL_AUTH_BASE = 'nexaauth:\/\/oauth\/authorize';/);
  assert.match(js, /const NCHAT_SESSION_STORAGE_KEY = 'claw800:nchat:nexa-session';/);
  assert.match(js, /const NCHAT_LOCAL_PROFILE_ID_STORAGE_KEY = 'claw800:nchat:local-profile-id';/);
  assert.match(js, /const NCHAT_LOCAL_PROFILE_STORAGE_KEY = 'claw800:nchat:local-profile';/);
  assert.match(js, /const NCHAT_LOCAL_DEMO_MESSAGES_STORAGE_KEY = 'claw800:nchat:local-demo-messages';/);
  assert.match(js, /const NCHAT_BOOTSTRAP_CACHE_STORAGE_KEY = 'claw800:nchat:bootstrap-cache';/);
  assert.match(js, /const NCHAT_CONVERSATION_CACHE_STORAGE_KEY = 'claw800:nchat:conversation-cache';/);
  assert.match(js, /function beginNexaLoginFlow\(/);
  assert.match(js, /function ensureLocalPreviewSession\(/);
  assert.match(js, /function loadLocalPreviewProfile\(/);
  assert.match(js, /function applyLocalPreviewBootstrap\(/);
  assert.match(js, /function appendLocalDemoMessage\(/);
  assert.match(js, /clearCachedSession\(state\.storage\);/);
  assert.match(js, /const localPreview = isLocalPreview\(\);/);
  assert.match(js, /const authCode = extractAuthCodeFromUrl\(\);/);
  assert.match(js, /if \(!localPreview && !authCode\) \{[\s\S]*clearCachedSession\(state\.storage\);[\s\S]*await clearServerSession\(\);[\s\S]*await beginNexaLoginFlow\(\)\.catch\(\(\) => \{\}\);[\s\S]*return;/);
  assert.match(js, /async function clearServerSession\(\)/);
  assert.match(js, /本地测试/);
  assert.match(js, /function setProfileFeedback\(/);
  assert.match(js, /\/api\/nchat\/session/);
  assert.match(js, /\/api\/nchat\/bootstrap/);
  assert.match(js, /\/api\/nchat\/profile/);
  assert.match(js, /\/api\/nchat\/search/);
  assert.match(js, /\/api\/nchat\/friends/);
  assert.match(js, /\/api\/nchat\/conversations\/.*\/messages/);
  assert.match(js, /\/api\/nchat\/conversations\/.*\/read/);
  assert.match(js, /\/api\/nchat\/events/);
  assert.match(js, /renderConversationList/);
  assert.match(js, /function updateProfileCloseVisibility\(state\)/);
  assert.match(js, /state\.elements\.profileClose\.hidden = Boolean\(state\.profileSetupRequired\);/);
  assert.match(js, /state\.elements\.profileClose\.addEventListener\('click'[\s\S]*if \(state\.profileSetupRequired\) return;[\s\S]*state\.elements\.profileModal\.hidden = true;/);
  assert.match(js, /function applyOptimisticProfile\(state, profile\)/);
  assert.match(js, /state\.pendingProfileAvatarUrl = avatarUrl;/);
  assert.match(js, /const avatarUrl = avatarFile \? String\(state\.pendingProfileAvatarUrl \|\| ''\) \|\| await compressAvatarFile\(avatarFile\) : fallbackAvatar;/);
  assert.match(js, /applyOptimisticProfile\(state, \{ nickname, avatarUrl \}\);[\s\S]*if \(isLocalPreview\(\)\) \{/);
  assert.match(js, /saveProfile\(\{ nickname, avatarUrl \}\)[\s\S]*\.then\(async \(response\) =>/);
  assert.match(js, /state\.pendingBootstrap = extractBootstrapFromResponse\(serverResponse\);/);
  assert.match(js, /function saveCachedBootstrap\(state, bootstrap\)/);
  assert.match(js, /function loadCachedBootstrap\(state\)/);
  assert.match(js, /function applyCachedBootstrapIfAvailable\(state\)/);
  assert.match(js, /function getConversationCacheKey\(state, conversationId\)/);
  assert.match(js, /function loadCachedConversationMessages\(state, conversationId\)/);
  assert.match(js, /function saveCachedConversationMessages\(state, conversationId, messages\)/);
  assert.match(js, /function upsertCachedConversationMessage\(state, conversationId, message\)/);
  assert.match(js, /function buildConversationSeedMessages\(row, cachedMessages = \[\]\)/);
  assert.match(js, /const cachedBootstrap = loadCachedBootstrap\(state\);[\s\S]*applyBootstrapPayload\(state, cachedBootstrap, \{ skipCache: true \}\);/);
  assert.match(js, /state\.session = authSession;[\s\S]*saveCachedSession\(state\.storage, authSession\);[\s\S]*applyCachedBootstrapIfAvailable\(state\);[\s\S]*const serverResponse = await requestJson\('\/api\/nchat\/session'/);
  assert.match(js, /applyCachedBootstrapIfAvailable\(state\);[\s\S]*connectRealtime\(state\);[\s\S]*await refreshBootstrap\(state\);/);
  assert.match(js, /state\.bootstrapRequestSeq = \(Number\(state\.bootstrapRequestSeq \|\| 0\) \|\| 0\) \+ 1;[\s\S]*const requestSeq = state\.bootstrapRequestSeq;/);
  assert.match(js, /if \(requestSeq !== state\.bootstrapRequestSeq\) \{[\s\S]*skipped:\s*true/);
  assert.match(js, /const immediateBootstrap = consumePendingBootstrap\(state\);/);
  assert.match(js, /if \(immediateBootstrap\) \{[\s\S]*applyBootstrapPayload\(state, immediateBootstrap\);[\s\S]*\} else \{[\s\S]*applyCachedBootstrapIfAvailable\(state\);[\s\S]*\}/);
  assert.match(js, /function upsertConversation\(/);
  assert.match(js, /function createOptimisticMessage\(/);
  assert.match(js, /const NCHAT_AVATAR_MAX_SIZE = 320;/);
  assert.match(js, /const NCHAT_AVATAR_JPEG_QUALITY = 0\.78;/);
  assert.match(js, /const NCHAT_REALTIME_POLL_INTERVAL_MS = 1000;/);
  assert.match(js, /function compressAvatarFile\(file\)/);
  assert.match(js, /canvas\.toDataURL\('image\/jpeg', NCHAT_AVATAR_JPEG_QUALITY\)/);
  assert.match(js, /button\.textContent = '连接中\.\.\.'/);
  assert.match(js, /state\.messages = \[\.\.\.\(state\.messages \|\| \[\]\), pendingMessage\]/);
  assert.match(js, /function appendRealtimeMessage\(state, message\)/);
  assert.match(js, /function incrementConversationUnread\(state, conversationId\)/);
  assert.match(js, /function clearConversationUnread\(state, conversationId\)/);
  assert.match(js, /async function runRealtimePoll\(state\)/);
  assert.match(js, /function startRealtimePolling\(state\)/);
  assert.match(js, /function stopRealtimePolling\(state\)/);
  assert.match(js, /function bindRealtimeVisibility\(state\)/);
  assert.match(js, /saveCachedConversationMessages\(state, state\.activeConversationId, rows\);/);
  assert.match(js, /clearConversationUnread\(state, normalizedId\);[\s\S]*if \(normalizedId === NCHAT_DEMO_CONVERSATION_ID\)/);
  assert.match(js, /const cachedMessages = loadCachedConversationMessages\(state, normalizedId\);[\s\S]*const seedMessages = buildConversationSeedMessages\(row, cachedMessages\);[\s\S]*if \(seedMessages\.length\) \{[\s\S]*state\.messages = seedMessages;[\s\S]*renderMessages\(state\);[\s\S]*\} else \{[\s\S]*state\.messages = \[\];[\s\S]*renderMessages\(state\);[\s\S]*\}[\s\S]*const history = await loadMessages\(normalizedId\);/);
  assert.match(js, /appendRealtimeMessage\(state, payload\.message\);[\s\S]*renderMessages\(state\);[\s\S]*markConversationRead\(state\.activeConversationId\)\.catch\(\(\) => null\);/);
  assert.match(js, /upsertCachedConversationMessage\(state, payload\.conversationId, \{[\s\S]*isSelf:\s*false[\s\S]*\}\);[\s\S]*incrementConversationUnread\(state, payload\.conversationId\);[\s\S]*renderConversationList\(state\);[\s\S]*refreshBootstrap\(state\)\.catch\(\(\) => null\);/);
  assert.match(js, /function syncActiveConversationMessages\(state\)/);
  assert.match(js, /source\.addEventListener\('nchat\.conversation-updated', async \(event\) => \{[\s\S]*await refreshBootstrap\(state\)\.catch\(\(\) => null\);[\s\S]*await syncActiveConversationMessages\(state\);/);
  assert.match(js, /connectRealtime\(state\);[\s\S]*startRealtimePolling\(state\);[\s\S]*bindRealtimeVisibility\(state\);[\s\S]*await refreshBootstrap\(state\);/);
  assert.match(js, /refreshBootstrap\(state\)\.catch\(\(\) => null\)/);
  assert.match(js, /applyUnreadBadge/);
  assert.match(js, /nchat-message-block__time/);
  assert.match(js, /我的客服/);
  assert.match(js, /demo-support/);
  assert.match(js, /请在 Nexa App 内打开 Nchat/);
});
