const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.join(__dirname, '..');
const configPath = path.join(rootDir, 'public', 'games-config.js');
const dbPath = path.join(rootDir, 'src', 'db.js');
const serverPath = path.join(rootDir, 'src', 'server.js');
const htmlPath = path.join(rootDir, 'public', 'nexa-escrow', 'index.html');
const cssPath = path.join(rootDir, 'public', 'nexa-escrow', 'style.css');
const jsPath = path.join(rootDir, 'public', 'nexa-escrow', 'script.js');
const adminHtmlPath = path.join(rootDir, 'public', 'admin.html');
const adminJsPath = path.join(rootDir, 'public', 'admin.js');

test('nexa-escrow game files exist', () => {
  assert.equal(fs.existsSync(htmlPath), true);
  assert.equal(fs.existsSync(cssPath), true);
  assert.equal(fs.existsSync(jsPath), true);
});

test('nexa-escrow shell keeps header fixed while panels scroll within remaining height', () => {
  const css = fs.readFileSync(cssPath, 'utf8');

  assert.match(css, /\.nexa-escrow-shell\s*\{[\s\S]*grid-template-rows:\s*auto auto minmax\(0,\s*1fr\)/);
  assert.match(css, /\.nexa-escrow-shell\s*\{[\s\S]*height:\s*100%/);
  assert.match(css, /\.nexa-escrow-panel\s*\{[\s\S]*height:\s*100%/);
  assert.match(css, /\.nexa-escrow-panel--scrollable\s*\{[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /\.nexa-escrow-panel--scrollable\s*\{[\s\S]*align-content:\s*start/);
  assert.match(css, /\.nexa-escrow-panel\[data-tab="create"\]\s*\{[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /\.nexa-escrow-panel\[data-tab="account"\]\s*\{[\s\S]*align-content:\s*start/);
  assert.match(css, /\.nexa-escrow-panel\[data-tab="account"\]\s*>\s*\.nexa-escrow-card\s*\{[\s\S]*align-self:\s*start/);
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.nexa-escrow-detail-grid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
});

test('nexa-escrow is listed in frontend config and backend defaults as a standalone page hidden from the public hub', () => {
  const config = fs.readFileSync(configPath, 'utf8');
  const db = fs.readFileSync(dbPath, 'utf8');
  const server = fs.readFileSync(serverPath, 'utf8');

  assert.match(config, /slug:\s*'nexa-escrow'/);
  assert.match(config, /name:\s*'Nexa 担保'/);
  assert.match(config, /showInGamesHub:\s*0/);
  assert.match(config, /route:\s*'\/nexa-escrow\/'/);
  assert.match(db, /slug:\s*'nexa-escrow'/);
  assert.match(server, /'nexa-escrow':\s*'\/nexa-escrow\/'/);
});

test('nexa-escrow html includes create and orders tabs plus escrow actions', () => {
  const html = fs.readFileSync(htmlPath, 'utf8');

  assert.match(html, /<title>Claw800 Nexa 担保<\/title>/);
  assert.match(html, /data-nexa-escrow-app/);
  assert.doesNotMatch(html, /id="nexaEscrowAuthStatus"/);
  assert.doesNotMatch(html, /data-locale-toggle=/);
  assert.doesNotMatch(html, /data-i18n="eyebrow"/);
  assert.doesNotMatch(html, /data-i18n="createHeadline"/);
  assert.match(html, /data-tab="create"/);
  assert.match(html, /data-tab="orders"/);
  assert.match(html, /data-tab="account"/);
  assert.match(html, /id="nexaEscrowRoleBuyer"/);
  assert.match(html, /id="nexaEscrowRoleSeller"/);
  assert.match(html, /id="nexaEscrowRoleSeller"[\s\S]*id="nexaEscrowRoleBuyer"/);
  assert.match(html, /id="nexaEscrowAmountInput"/);
  assert.match(html, /id="nexaEscrowCounterpartyInput"/);
  assert.match(html, /class="nexa-escrow-field nexa-escrow-field--inline"/);
  assert.match(html, /id="nexaEscrowDescriptionInput"/);
  assert.match(html, /id="nexaEscrowDescriptionInput"[\s\S]*maxlength="30"/);
  assert.match(html, /id="nexaEscrowFeeHint"/);
  assert.match(html, /注:最低 1U，最高 100000U，手续费0/);
  assert.match(html, /id="nexaEscrowCreateButton"[\s\S]*data-i18n="createAndPayAction"[\s\S]*确认发起并付款/);
  assert.match(html, /data-order-filter="all"/);
  assert.match(html, /data-order-filter="active"/);
  assert.match(html, /data-order-filter="disputed"/);
  assert.match(html, /data-order-filter="cancelled"/);
  assert.match(html, /data-order-filter="completed"/);
  assert.match(html, /id="nexaEscrowOrdersList"/);
  assert.match(html, /id="nexaEscrowOrdersPullToRefresh"/);
  assert.match(html, /id="nexaEscrowOrdersPullSpinner"/);
  assert.match(html, /id="nexaEscrowAccountPullToRefresh"/);
  assert.match(html, /id="nexaEscrowAccountPullSpinner"/);
  assert.match(html, /id="nexaEscrowOrderDetail"/);
  assert.match(html, /id="nexaEscrowPrimaryAction"/);
  assert.match(html, /id="nexaEscrowSecondaryAction"/);
  assert.match(html, /id="nexaEscrowHeaderCode"/);
  assert.match(html, /id="nexaEscrowHeaderCopy"/);
  assert.doesNotMatch(html, />n000000</);
  assert.match(html, /id="nexaEscrowWithdrawBtn"/);
  assert.match(html, /id="nexaEscrowNicknameInput"/);
  assert.match(html, /id="nexaEscrowNicknameSaveBtn"/);
  assert.match(html, /id="nexaEscrowNicknameHint"/);
  assert.match(html, /id="nexaEscrowLatestWithdrawal"/);
  assert.match(html, /id="nexaEscrowWithdrawalList"/);
  assert.match(html, /id="nexaEscrowWithdrawalPagination"/);
  assert.match(html, /id="nexaEscrowWithdrawalPrev"/);
  assert.match(html, /id="nexaEscrowWithdrawalNext"/);
  assert.match(html, /id="nexaEscrowWithdrawalPageInfo"/);
  assert.match(html, /id="nexaEscrowWithdrawModal"/);
  assert.match(html, /id="nexaEscrowWithdrawAmountInput"/);
  assert.match(html, /id="nexaEscrowAccountStatus"/);
  assert.match(html, /id="nexaEscrowCodeModal"/);
  assert.match(html, /id="nexaEscrowCodeModalInput"/);
  assert.match(html, /id="nexaEscrowCodeModalHint"/);
  assert.doesNotMatch(html, /nexa-escrow-back/);
  assert.match(html, /\/nexa-escrow\/script\.js/);
});

test('nexa-escrow script includes Nexa auth, escrow bootstrap, order, and payment hooks', () => {
  const js = fs.readFileSync(jsPath, 'utf8');

  assert.match(js, /const NEXA_ESCROW_SESSION_STORAGE_KEY = 'claw800:nexa-escrow:nexa-session';/);
  assert.match(js, /const NEXA_ESCROW_PENDING_PAYMENT_STORAGE_KEY = 'claw800:nexa-escrow:pending-payment';/);
  assert.match(js, /const NEXA_ESCROW_CODE_MODAL_STORAGE_KEY = 'claw800:nexa-escrow:code-modal:'/);
  assert.match(js, /const MAX_NEXA_ESCROW_SESSION_RETENTION_MS = 30 \* 24 \* 60 \* 60 \* 1000;/);
  assert.match(js, /const NEXA_PROTOCOL_AUTH_BASE = 'nexaauth:\/\/oauth\/authorize';/);
  assert.match(js, /const NEXA_PROTOCOL_ORDER_BASE = 'nexaauth:\/\/order';/);
  assert.match(js, /\/api\/nexa-escrow\/session/);
  assert.match(js, /\/api\/nexa-escrow\/session\/logout/);
  assert.match(js, /\/api\/nexa-escrow\/bootstrap/);
  assert.match(js, /\/api\/nexa-escrow\/orders/);
  assert.match(js, /\/api\/nexa-escrow\/payment\/create/);
  assert.match(js, /\/api\/nexa-escrow\/payment\/query/);
  assert.match(js, /\/api\/nexa-escrow\/orders\/action/);
  assert.match(js, /function beginNexaLoginFlow\(/);
  assert.match(js, /async function clearServerSession\(\)/);
  assert.match(js, /function hasRecentPendingPaymentReturn\(/);
  assert.match(js, /const isPaymentReturn = hasRecentPendingPaymentReturn\(appState\.storage\);/);
  assert.match(js, /hasNexaEnvironment\(\) && !synced && !isPaymentReturn/);
  assert.match(js, /function createEscrowOrder\(/);
  assert.match(js, /function beginEscrowPayment\(/);
  assert.match(js, /function settlePendingEscrowPayment\(/);
  assert.match(js, /if \(String\(response\.status \|\| ''\)\.trim\(\)\.toUpperCase\(\) === 'SUCCESS'\) \{[\s\S]*switchTab\(appState, 'orders'\);/);
  assert.match(js, /function submitEscrowAction\(/);
  assert.match(js, /appState\.orders = mergeOrder\(appState\.orders, response\.order\);[\s\S]*renderOrderDetail\(appState\);[\s\S]*renderOrders\(appState\);/);
  assert.match(js, /function filterOrders\(/);
  assert.match(js, /function refreshEscrowOrders\(/);
  assert.match(js, /function refreshEscrowAccount\(/);
  assert.match(js, /function refreshCurrentEscrowTab\(/);
  assert.match(js, /NEXA_ESCROW_PULL_REFRESH_TRIGGER_PX/);
  assert.match(js, /function openEscrowCodeModal\(/);
  assert.match(js, /function closeOrderDetail\(/);
  assert.match(js, /function openEscrowOrderFromList\(/);
  assert.match(js, /function getEscrowFieldAnchor\(/);
  assert.match(js, /function scrollEscrowFieldIntoView\(/);
  assert.match(js, /function updateEscrowKeyboardInset\(/);
  assert.match(js, /visualViewport\?\.addEventListener\?\.\('resize'/);
  assert.match(js, /renderOrderDetail\(appState\);\s*renderOrders\(appState\);/);
  assert.match(js, /roleBuyer: '我要卖u\\n付u买物'/);
  assert.match(js, /roleSeller: '我要买u\\n收u发货'/);
  assert.match(js, /role: 'seller'/);
  assert.match(js, /viewerBuyer: '我是买家'/);
  assert.match(js, /viewerSeller: '我是卖家'/);
  assert.match(js, /descriptionTooLong: '交易描述最多 30 个字'/);
  assert.match(js, /invalidAmount: '金额最多支持两位小数'/);
  assert.match(js, /function normalizeMoneyInputValue\(/);
  assert.match(js, /button\.classList\.toggle\('is-buyer', isActive && appState\.role === 'buyer'\)/);
  assert.match(js, /button\.classList\.toggle\('is-seller', isActive && appState\.role === 'seller'\)/);
  assert.match(js, /createButton\.classList\.toggle\('is-buyer', appState\.role === 'buyer'\)/);
  assert.match(js, /createButton\.classList\.toggle\('is-seller', appState\.role === 'seller'\)/);
  assert.match(js, /nicknameLabel: '昵称:'/);
  assert.match(js, /nicknameHint: '昵称一旦生成，无法修改'/);
  assert.match(js, /nicknameSaved: '昵称已保存'/);
  assert.match(js, /nicknameLocked: '昵称已生成，无法修改'/);
  assert.match(js, /nicknameRequired: '请填写昵称'/);
  assert.match(js, /nicknameInvalid: '昵称最多 6 个中文或 12 个字母数字'/);
  assert.match(js, /nicknamePunctuation: '昵称不能输入标点符号'/);
  assert.match(js, /nicknameTooLong: '昵称最多 6 个中文或 12 个字母数字'/);
  assert.match(js, /function getEscrowNicknameValidationError\(/);
  assert.match(js, /ESCROW_NICKNAME_PUNCTUATION/);
  assert.match(js, /nicknameTaken: '此昵称已被占用，请重新填写'/);
  assert.match(js, /\/api\/nexa-escrow\/profile\/nickname/);
  assert.match(js, /if \(!String\(appState\.account\?\.escrowNickname \|\| ''\)\.trim\(\)\) \{/);
  assert.match(js, /function maskEscrowNickname\(/);
  assert.match(js, /function formatEscrowIdentityLine\(/);
  assert.match(js, /if \(!normalized\) return 'nexa玩家';/);
  assert.match(js, /担保号:/);
  assert.match(js, /function describeViewerRole\(/);
  assert.match(js, /function getViewerRoleType\(/);
  assert.match(js, /paymentCountdown: '付款倒计时'/);
  assert.match(js, /shipCountdown: '等发货倒计时'/);
  assert.match(js, /receiptCountdown: '倒计时确认收货'/);
  assert.match(js, /function formatEscrowCountdown\(/);
  assert.match(js, /function getEscrowPaymentCountdownText\(/);
  assert.match(js, /function getEscrowShipCountdownText\(/);
  assert.match(js, /function getEscrowReceiptCountdownText\(/);
  assert.match(js, /orderTickTimer:/);
  assert.match(js, /startEscrowOrderTick\(appState\)/);
  assert.match(js, /autoReleaseAt = String\(order\?\.autoReleaseAt \|\| ''\)\.trim\(\)/);
  assert.match(js, /nexa-escrow-order-item__initiator--\$\{getViewerRoleType\(appState, order\)\}/);
  assert.match(js, /closeDetail: '关闭详情'/);
  assert.match(js, /hasExpandedDetail && order\.tradeCode === appState\.selectedTradeCode \? t\(appState\.locale, 'closeDetail'\) : t\(appState\.locale, 'viewDetail'\)/);
  assert.match(js, /function applyTranslations\(/);
  assert.match(js, /function copyEscrowCode\(/);
  assert.match(js, /headerCode\.classList\.toggle\('is-loading', !escrowCode\)/);
  assert.match(js, /headerCopy\.classList\.toggle\('is-loading', !escrowCode\)/);
  assert.match(js, /function beginEscrowWithdrawFlow\(/);
  assert.match(js, /\/api\/nexa-escrow\/withdraw\/create/);
  assert.match(js, /\/api\/nexa-escrow\/withdraw\/query/);
  assert.match(js, /latestWithdrawalLabel: '最新提现记录'/);
  assert.match(js, /withdrawStatusReviewPending: '待审核'/);
  assert.match(js, /withdrawStatusPending: '处理中'/);
  assert.match(js, /withdrawStatusSuccess: '已到账'/);
  assert.match(js, /const NEXA_ESCROW_WITHDRAW_POLL_INTERVAL_MS = 15000;/);
  assert.match(js, /lastWithdrawalPollAt:\s*0/);
  assert.match(js, /syncLatestEscrowWithdrawalStatus\(appState\)\.catch\(\(\) => \{\}\);/);
  assert.match(js, /const NEXA_ESCROW_WITHDRAWALS_PER_PAGE = 5;/);
  assert.match(js, /const DEFAULT_NEXA_ESCROW_SETTINGS = Object\.freeze\(\{/);
  assert.match(js, /minAmount:\s*'1\.00'/);
  assert.match(js, /maxAmount:\s*'100000\.00'/);
  assert.match(js, /feePermille:\s*'0'/);
  assert.match(js, /amountTooLow: '金额不能低于最低担保金额'/);
  assert.match(js, /amountTooHigh: '金额不能超过最高担保金额'/);
  assert.match(js, /function normalizeEscrowSettings\(/);
  assert.match(js, /function formatEscrowFeeHint\(/);
  assert.match(js, /getEscrowAmountTooLowText\(appState\)/);
  assert.match(js, /getEscrowAmountTooHighText\(appState\)/);
  assert.match(js, /feeHint:\s*root\.querySelector\('#nexaEscrowFeeHint'\)/);
  assert.match(js, /appState\.settings = normalizeEscrowSettings\(response\.settings \|\| \{\}\);/);
  assert.match(js, /function formatEscrowLocalDateTime\(/);
  assert.match(js, /const minAmount = String\(settings\.minAmount \|\| '0'\)\.split\('\.'\)\[0\] \|\| '0';/);
  assert.match(js, /const maxAmount = String\(settings\.maxAmount \|\| '0'\)\.split\('\.'\)\[0\] \|\| '0';/);
  assert.match(js, /function syncLatestEscrowWithdrawalStatus\(/);
  assert.match(js, /withdrawalList: root\.querySelector\('#nexaEscrowWithdrawalList'\)/);
  assert.match(js, /withdrawalPrev: root\.querySelector\('#nexaEscrowWithdrawalPrev'\)/);
  assert.match(js, /withdrawalNext: root\.querySelector\('#nexaEscrowWithdrawalNext'\)/);
  assert.match(js, /withdrawalPageInfo: root\.querySelector\('#nexaEscrowWithdrawalPageInfo'\)/);
  assert.match(js, /orderFilterButtons/);
  assert.match(js, /AWAITING_PAYMENT', 'PAYMENT_PENDING', 'FUNDED', 'DELIVERED'/);
  assert.match(js, /actionDispute/);
  assert.match(js, /actionConfirmReceipt/);
  assert.match(js, /actionCancelledDone: '已取消'/);
  assert.match(js, /confirmCancelPrompt: '确认取消这笔订单吗？'/);
  assert.match(js, /const showCancelledInfo = normalizedStatus === 'CANCELLED';/);
  assert.match(js, /const sellerDeliveredDisputeAction = showDeliveredInfo && primaryAction === 'dispute' \? primaryAction : '';/);
  assert.match(js, /const showCompletedDisputeOnly = showCompletedInfo && primaryAction === 'dispute';/);
  assert.match(js, /const effectivePrimaryAction = showDeliveredInfo \|\| showCompletedInfo \? '' : primaryAction;/);
  assert.match(js, /const showFundedSellerOnlyDeliver = normalizedStatus === 'FUNDED' && normalizedViewerRole === 'seller';/);
  assert.match(js, /const effectiveSecondaryAction = showFundedSellerOnlyDeliver[\s\S]*showDeliveredInfo[\s\S]*sellerDeliveredDisputeAction[\s\S]*showCompletedInfo \? '' : secondaryAction/);
  assert.match(js, /showCancelledInfo\s*\?\s*t\(appState\.locale, 'actionCancelledDone'\)/);
  assert.match(js, /primaryAction\.hidden = !effectivePrimaryAction \|\| showCancelledInfo/);
  assert.doesNotMatch(js, /已登录/);
  assert.match(fs.readFileSync(cssPath, 'utf8'), /\.nexa-escrow-order-item__desc\s*\{[\s\S]*white-space:\s*nowrap/);
  assert.match(fs.readFileSync(cssPath, 'utf8'), /\.nexa-escrow-order-item__countdown\s*\{/);
  assert.match(fs.readFileSync(cssPath, 'utf8'), /\.nexa-escrow-field--inline\s*\{[\s\S]*grid-template-columns:\s*110px minmax\(0,\s*1fr\)/);
  assert.match(fs.readFileSync(cssPath, 'utf8'), /\.nexa-escrow-role-toggle__item\.is-active\.is-buyer,[\s\S]*\.nexa-escrow-primary\.is-buyer/);
  assert.match(fs.readFileSync(cssPath, 'utf8'), /\.nexa-escrow-role-toggle__item\.is-active\.is-seller,[\s\S]*\.nexa-escrow-primary\.is-seller/);
});

test('admin panel includes nexa escrow orders, users, and withdrawal review entry points', () => {
  const html = fs.readFileSync(adminHtmlPath, 'utf8');
  const js = fs.readFileSync(adminJsPath, 'utf8');

  assert.match(html, /id="navNexaEscrowOrders"/);
  assert.match(html, /id="navNexaEscrowUsers"/);
  assert.match(html, /id="navNexaEscrowWithdrawals"/);
  assert.match(html, /id="adminNexaEscrowSection"/);
  assert.match(html, /id="adminNexaEscrowUsersSection"/);
  assert.match(html, /id="adminNexaEscrowWithdrawalsSection"/);
  assert.match(html, /id="nexaEscrowOrdersList"/);
  assert.match(html, /id="nexaEscrowUsersList"/);
  assert.match(html, /id="nexaEscrowWithdrawalsList"/);
  assert.match(html, /name="nexaEscrowMinAmount"/);
  assert.match(html, /name="nexaEscrowMaxAmount"/);
  assert.match(html, /name="nexaEscrowFeePermille"/);
  assert.match(js, /const adminNexaEscrowUsersSection = document\.getElementById\('adminNexaEscrowUsersSection'\);/);
  assert.match(js, /const adminNexaEscrowWithdrawalsSection = document\.getElementById\('adminNexaEscrowWithdrawalsSection'\);/);
  assert.match(js, /const nexaEscrowUsersList = document\.getElementById\('nexaEscrowUsersList'\);/);
  assert.match(js, /const nexaEscrowWithdrawalsList = document\.getElementById\('nexaEscrowWithdrawalsList'\);/);
  assert.match(js, /requestTutorialJson\(\['\/api\/admin\/nexa-escrow-orders'\]/);
  assert.match(js, /requestTutorialJson\(\['\/api\/admin\/nexa-escrow-users'\]/);
  assert.match(js, /requestTutorialJson\(\['\/api\/admin\/nexa-escrow-withdrawals'\]/);
  assert.match(js, /nexaEscrowMinAmount:/);
  assert.match(js, /nexaEscrowMaxAmount:/);
  assert.match(js, /nexaEscrowFeePermille:/);
  assert.match(js, /requestTutorialJson\(\[`\/api\/admin\/nexa-escrow-users\/\$\{encodeURIComponent\(String\(userId\)\)\}\/code`\]/);
  assert.match(js, /requestTutorialJson\(\[`\/api\/admin\/nexa-escrow-withdrawals\/\$\{encodeURIComponent\(partnerOrderNo\)\}\/approve`\]/);
  assert.match(js, /requestTutorialJson\(\[`\/api\/admin\/nexa-escrow-withdrawals\/\$\{encodeURIComponent\(partnerOrderNo\)\}\/reject`\]/);
  assert.match(js, /nexaEscrowResolveSeller:\s*'资金给卖方'/);
  assert.match(js, /nexaEscrowResolveBuyer:\s*'资金给买方'/);
  assert.match(js, /return '申诉中'/);
});
