const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.join(__dirname, '..');
const htmlPath = path.join(rootDir, 'public', 'xiangqi', 'index.html');
const cssPath = path.join(rootDir, 'public', 'xiangqi', 'style.css');
const jsPath = path.join(rootDir, 'public', 'xiangqi', 'script.js');
const configPath = path.join(rootDir, 'public', 'games-config.js');
const dbPath = path.join(rootDir, 'src', 'db.js');
const serverPath = path.join(rootDir, 'src', 'server.js');

test('xiangqi game files exist', () => {
  assert.equal(fs.existsSync(htmlPath), true);
  assert.equal(fs.existsSync(cssPath), true);
  assert.equal(fs.existsSync(jsPath), true);
});

test('xiangqi game is listed in games config and backend defaults', () => {
  const config = fs.readFileSync(configPath, 'utf8');
  const db = fs.readFileSync(dbPath, 'utf8');
  const server = fs.readFileSync(serverPath, 'utf8');

  assert.match(config, /slug:\s*'xiangqi'/);
  assert.match(config, /name:\s*'中国象棋在线'/);
  assert.match(config, /route:\s*'\/xiangqi\/'/);
  assert.match(config, /item\.is_enabled && item\.slug !== 'xiangqi'/);
  assert.match(db, /slug:\s*'xiangqi'/);
  assert.match(server, /xiangqi:\s*'\/xiangqi\/'/);
});

test('xiangqi html includes mobile wallet, room, and board sections', () => {
  const html = fs.readFileSync(htmlPath, 'utf8');

  assert.match(html, /game-tip\.css\?v=/);
  assert.match(html, /game-tip\.js\?v=/);
  assert.match(html, /games-config\.js\?v=/);
  assert.doesNotMatch(html, /id="xiangqiLoginBtn"/);
  assert.doesNotMatch(html, /id="xiangqiWelcomeName"/);
  assert.match(html, />象棋在线余额</);
  assert.doesNotMatch(html, />我的余额</);
  assert.match(html, /id="xiangqiWalletAvailable"/);
  assert.doesNotMatch(html, /id="xiangqiWalletFrozen"/);
  assert.match(html, /id="xiangqiLedgerBtn"/);
  assert.match(html, /id="xiangqiLedgerBtn"[^>]*>明细</);
  assert.match(html, /id="xiangqiDepositBtn"/);
  assert.match(html, /id="xiangqiWithdrawBtn"/);
  assert.match(html, /id="xiangqiDepositBtn"[\s\S]*?id="xiangqiWithdrawBtn"/);
  assert.match(html, /id="xiangqiWithdrawBtn"[^>]*>提现</);
  assert.match(html, /id="xiangqiLedgerModal"/);
  assert.match(html, /id="xiangqiLedgerList"/);
  assert.match(html, /id="xiangqiLedgerCloseBtn"/);
  assert.match(html, /id="xiangqiAmountModal"/);
  assert.match(html, /id="xiangqiDrawConfirmModal"/);
  assert.match(html, /id="xiangqiDrawConfirmAcceptBtn"/);
  assert.match(html, /id="xiangqiDrawConfirmRejectBtn"/);
  assert.match(html, /id="xiangqiAmountInput"/);
  assert.match(html, /inputmode="decimal"/);
  assert.match(html, /pattern="\[0-9\]\*\[.,\]\?\[0-9\]\*"/);
  assert.match(html, /id="xiangqiAmountConfirmBtn"/);
  assert.match(html, /id="xiangqiAmountCancelBtn"/);
  assert.match(html, /id="xiangqiCreateStake"/);
  assert.match(html, /type="hidden"[^>]*id="xiangqiCreateStake"|id="xiangqiCreateStake"[^>]*type="hidden"/);
  assert.match(html, /data-stake-preset="1"/);
  assert.match(html, /data-stake-preset="5"/);
  assert.match(html, /data-stake-preset="10"/);
  assert.doesNotMatch(html, /data-stake-preset="50"/);
  assert.doesNotMatch(html, /data-stake-preset="100"/);
  assert.doesNotMatch(html, /data-stake-preset="500"/);
  assert.match(html, /id="xiangqiCreateTimeControl"/);
  assert.match(html, /type="hidden"[^>]*id="xiangqiCreateTimeControl"|id="xiangqiCreateTimeControl"[^>]*type="hidden"/);
  assert.match(html, /data-time-preset="10"/);
  assert.match(html, /data-time-preset="15"/);
  assert.match(html, /data-time-preset="30"/);
  assert.match(html, /class="xiangqi-create-options"/);
  assert.match(html, /id="xiangqiCreateRoomBtn"/);
  assert.match(html, /id="xiangqiJoinRoomCode"/);
  assert.match(html, /id="xiangqiJoinRoomCode"[^>]*inputmode="numeric"/);
  assert.match(html, /id="xiangqiJoinRoomCode"[^>]*pattern="\[0-9\]\*"/);
  assert.match(html, /class="xiangqi-room-input-wrap"[\s\S]*?id="xiangqiJoinRoomCode"[\s\S]*?id="xiangqiJoinRoomClearBtn"/);
  assert.match(html, /id="xiangqiJoinRoomBtn"/);
  assert.doesNotMatch(html, /查看本局 stake 与局时/);
  assert.doesNotMatch(html, /提现回 Nexa/);
  assert.match(html, /class="xiangqi-board-stage"/);
  assert.match(html, /id="xiangqiBoardOverlay"/);
  assert.match(html, /id="xiangqiBoardOverlayMessage"/);
  assert.match(html, /id="xiangqiBoardOverlayDetail"/);
  assert.match(html, /id="xiangqiStartMatchBtn"/);
  assert.match(html, /id="xiangqiRematchBtn"/);
  assert.match(html, /id="xiangqiConfirmRematchBtn"/);
  assert.match(html, /id="xiangqiReturnLobbyBtn"/);
  assert.match(html, /xiangqi-player-card--footer/);
  assert.match(html, /id="xiangqiBoard"/);
  assert.match(html, /class="xiangqi-board-head"[\s\S]*?id="xiangqiTopSide"[\s\S]*?id="xiangqiTopPlayer"[\s\S]*?id="xiangqiRoomBadge"/);
  assert.match(html, /id="xiangqiRoomBadge">房间号:\s*<span class="xiangqi-room-badge__value">000000<\/span><\/span>/);
  assert.match(html, /class="xiangqi-board-foot"[\s\S]*?id="xiangqiMatchStatus"[\s\S]*?id="xiangqiBottomSide"[\s\S]*?id="xiangqiBottomPlayer"/);
  assert.match(html, /class="xiangqi-action-bar"[\s\S]*?id="xiangqiCancelRoomBtn"[\s\S]*?id="xiangqiBottomSide"[\s\S]*?id="xiangqiBottomPlayer"/);
  assert.doesNotMatch(html, /id="xiangqiActiveRoomCard"/);
  assert.doesNotMatch(html, /id="xiangqiMyRoomBtn"/);
  assert.match(html, /id="xiangqiCancelRoomBtn"/);
  assert.doesNotMatch(html, /id="xiangqiActionDrawRejectBtn"/);
  assert.match(html, /class="xiangqi-action-bar"[\s\S]*?id="xiangqiActionResignBtn"[\s\S]*?id="xiangqiActionDrawBtn"[\s\S]*?id="xiangqiActionCopyRoomBtn"[\s\S]*?id="xiangqiCancelRoomBtn"/);
  assert.match(html, /id="xiangqiActionResignBtn"/);
  assert.match(html, /id="xiangqiActionDrawBtn"/);
});

test('xiangqi script bootstraps page state and board coordinates', () => {
  const js = fs.readFileSync(jsPath, 'utf8');

  assert.match(js, /const GAME_SLUG = 'xiangqi';/);
  assert.match(js, /const FILE_LABELS = \['9', '8', '7', '6', '5', '4', '3', '2', '1'\];/);
  assert.match(js, /const RANK_LABELS = \['9', '8', '7', '6', '5', '4', '3', '2', '1', '0'\];/);
  assert.match(js, /const NEXA_PROTOCOL_AUTH_BASE = 'nexaauth:\/\/oauth\/authorize';/);
  assert.match(js, /const XIANGQI_MOVE_AUDIO_SRC = '\/audio\/muyu-strike\.mp3';/);
  assert.match(js, /const XIANGQI_BROWSER_LOCAL_OPEN_ID = 'xiangqi-browser-local';/);
  assert.doesNotMatch(js, /XIANGQI_DEMO_OPEN_ID/);
  assert.doesNotMatch(js, /XIANGQI_DEMO_STARTING_BALANCE/);
  assert.match(js, /function isLocalDevelopmentHost\(/);
  assert.match(js, /window\.location\.hostname/);
  assert.match(js, /return hostname === 'localhost' \|\| hostname === '127\.0\.0\.1';/);
  assert.match(js, /function buildNexaAuthorizeUrl\(/);
  assert.match(js, /function buildNexaPaymentUrl\(/);
  assert.match(js, /function launchNexaUrl\(/);
  assert.match(js, /window\.location\.href = targetUrl;/);
  assert.match(js, /function exchangeSessionFromUrlCode\(/);
  assert.match(js, /function beginLoginFlow\(/);
  assert.match(js, /async function ensureAuthorizedForRoomAction\(/);
  assert.match(js, /if \(!isNexaAppEnvironment\(\) && isLocalDevelopmentHost\(\)\) \{/);
  assert.match(js, /openId:\s*XIANGQI_BROWSER_LOCAL_OPEN_ID/);
  assert.match(js, /const XIANGQI_PENDING_ACTION_KEY = 'claw800_xiangqi_pending_action_v1';/);
  assert.match(js, /function savePendingAction\(/);
  assert.match(js, /function loadPendingAction\(/);
  assert.match(js, /function clearPendingAction\(/);
  assert.match(js, /async function resumePendingAction\(/);
  assert.match(js, /function restoreActiveRoom\(/);
  assert.match(js, /function updateLoginButtonState\(/);
  assert.match(js, /if \(ui\.withdrawBtn\) \{\s*ui\.withdrawBtn\.disabled = !isNexaAppEnvironment\(\);\s*\}/);
  assert.match(js, /launchNexaUrl\(buildNexaAuthorizeUrl\(\)\)/);
  assert.match(js, /amountModal: document\.getElementById\('xiangqiAmountModal'\)/);
  assert.match(js, /ledgerBtn: document\.getElementById\('xiangqiLedgerBtn'\)/);
  assert.match(js, /ledgerModal: document\.getElementById\('xiangqiLedgerModal'\)/);
  assert.match(js, /ledgerList: document\.getElementById\('xiangqiLedgerList'\)/);
  assert.match(js, /drawConfirmModal: document\.getElementById\('xiangqiDrawConfirmModal'\)/);
  assert.match(js, /rematchBtn: document\.getElementById\('xiangqiRematchBtn'\)/);
  assert.match(js, /confirmRematchBtn: document\.getElementById\('xiangqiConfirmRematchBtn'\)/);
  assert.match(js, /returnLobbyBtn: document\.getElementById\('xiangqiReturnLobbyBtn'\)/);
  assert.match(js, /drawConfirmAcceptBtn: document\.getElementById\('xiangqiDrawConfirmAcceptBtn'\)/);
  assert.match(js, /drawConfirmRejectBtn: document\.getElementById\('xiangqiDrawConfirmRejectBtn'\)/);
  assert.match(js, /amountInput: document\.getElementById\('xiangqiAmountInput'\)/);
  assert.match(js, /joinRoomClearBtn: document\.getElementById\('xiangqiJoinRoomClearBtn'\)/);
  assert.match(js, /function sanitizeMoneyInput\(/);
  assert.match(js, /function syncJoinRoomClearButton\(/);
  assert.match(js, /function openAmountModal\(/);
  assert.match(js, /function closeAmountModal\(/);
  assert.match(js, /function getLedgerEntryPresentation\(/);
  assert.match(js, /const withdrawalStatus = String\(item\?\.withdrawalStatus \|\| ''\)\.trim\(\)\.toLowerCase\(\);/);
  assert.match(js, /if \(type === 'withdraw_debit'\) \{/);
  assert.match(js, /label = '已经到账';/);
  assert.match(js, /label = '提现中';[\s\S]*?detailText = '24小时内审核到账';/);
  assert.match(js, /async function openLedgerModal\(/);
  assert.match(js, /function closeLedgerModal\(/);
  assert.match(js, /async function startRematch\(/);
  assert.match(js, /async function confirmRematch\(/);
  assert.match(js, /async function returnToLobby\(/);
  assert.match(js, /const previousRoomCode = String\(state\.room\?\.roomCode \|\| ''\)\.trim\(\)\.toUpperCase\(\);/);
  assert.match(js, /if \(ui\.joinRoomCode\) ui\.joinRoomCode\.value = previousRoomCode;/);
  assert.match(js, /syncJoinRoomClearButton\(\);/);
  assert.match(js, /\/api\/xiangqi\/wallet\/ledger\?userId=/);
  assert.match(js, /function openDrawConfirmModal\(/);
  assert.match(js, /function closeDrawConfirmModal\(/);
  assert.match(js, /function requestAmount\(/);
  assert.match(js, /function getRoomStatusLabel\(/);
  assert.match(js, /if \(normalizedStatus === 'WAITING'\) return '等待加入';/);
  assert.match(js, /if \(normalizedStatus === 'READY'\) return '等待开始';/);
  assert.match(js, /if \(normalizedStatus === 'PLAYING'\) return '对局中';/);
  assert.match(js, /if \(normalizedStatus === 'FINISHED'\) return '已结束';/);
  assert.match(js, /setStatus\('请在 Nexa 内充值。'\);\s*return;/);
  assert.match(js, /savePendingAction\(\{\s*type:\s*'deposit',\s*amount/);
  assert.match(js, /setStatus\('请先完成 Nexa 登录授权。'\);\s*beginLoginFlow\(\);\s*return;/);
  assert.match(js, /launchNexaUrl\(buildNexaPaymentUrl\(response\.payment\)\)/);
  assert.match(js, /function buildPreviewPieces\(/);
  assert.match(js, /function primeMoveAudio\(/);
  assert.match(js, /function playMoveSound\(/);
  assert.match(js, /async function unlockMoveSound\(/);
  assert.match(js, /state\.moveAudioUnlocked/);
  assert.match(js, /function speakXiangqiCue\(/);
  assert.match(js, /function speakText\(/);
  assert.match(js, /function speakStartPrompt\(/);
  assert.match(js, /function speakRedFirstTurnPrompt\(/);
  assert.match(js, /function speakFinishedMatchResult\(/);
  assert.match(js, /window\.speechSynthesis/);
  assert.match(js, /utterance\.text = cue === 'check' \? '将军' : '吃';/);
  assert.match(js, /您是红方，您先下棋/);
  assert.match(js, /红方胜利/);
  assert.match(js, /黑方胜利/);
  assert.match(js, /本局和棋/);
  assert.match(js, /房主请点击再来一局/);
  assert.match(js, /等待房主再来一局/);
  assert.match(js, /请确认再来一局/);
  assert.match(js, /new Audio\(XIANGQI_MOVE_AUDIO_SRC\)/);
  assert.match(js, /function syncRoomUrl\(/);
  assert.match(js, /function syncTimePresetButtons\(/);
  assert.match(js, /function cancelWaitingRoom\(/);
  assert.match(js, /if \(!await ensureAuthorizedForRoomAction\(\)\) return;/);
  assert.match(js, /savePendingAction\(\{\s*type:\s*'join'/);
  assert.match(js, /savePendingAction\(\{\s*type:\s*'create'/);
  assert.match(js, /if \(String\(pendingAction\.type\) === 'deposit'\) \{/);
  assert.match(js, /await beginDepositFlow\(String\(pendingAction\.amount \|\| ''\)\.trim\(\)\);/);
  assert.match(js, /clearPendingAction\(\);\s*await refreshWallet\(\);\s*await refreshRoom\(response\.roomCode\);/);
  assert.match(js, /clearPendingAction\(\);\s*await refreshWallet\(\);\s*await refreshRoom\(roomCode\);/);
  assert.match(js, /await resumePendingAction\(\)\.catch\(\(\) => \{\}\);/);
  assert.match(js, /syncRoomUrl\(null\)/);
  assert.match(js, /function buildBoardMarkup\(/);
  assert.doesNotMatch(js, /xiangqi-board__coord/);
  assert.match(js, /xiangqi-board__svg-wrap/);
  assert.match(js, /xiangqi-board__grid-lines/);
  assert.match(js, /xiangqi-board__palace-lines/);
  assert.match(js, /xiangqi-board__river-text/);
  assert.match(js, /function getPlayerCardsViewModel\(/);
  assert.match(js, /if \(matchStatus !== 'PLAYING' && matchStatus !== 'FINISHED'\) return '';/);
  assert.match(js, /label: '待分边'/);
  assert.match(js, /function renderRoomSummary\(/);
  assert.match(js, /状态 \$\{getRoomStatusLabel\(state\.room\.status\)\}。/);
  assert.doesNotMatch(js, /状态 \$\{state\.room\.status\}。/);
  assert.doesNotMatch(js, /stake 与局时/);
  assert.doesNotMatch(js, /function renderDrawActionState\(/);
  assert.match(js, /function getRoomOverlayState\(/);
  assert.match(js, /if \(roomStatus === 'DISBANDED'\)/);
  assert.match(js, /message: '房间已解除'/);
  assert.match(js, /if \(roomStatus === 'DISBANDED'\) \{[\s\S]*?showFinishedActions:\s*true,[\s\S]*?showReturnLobby:\s*true/);
  assert.match(js, /function getRematchCountdownSeconds\(/);
  assert.match(js, /function renderBoardOverlay\(/);
  assert.match(js, /state\.lastStartPromptKey/);
  assert.match(js, /state\.lastRedFirstTurnPromptKey/);
  assert.match(js, /speakStartPrompt\(\);/);
  assert.match(js, /function maybeSpeakRedFirstTurnPrompt\(/);
  assert.match(js, /speakRedFirstTurnPrompt\(\);/);
  assert.match(js, /state\.room\?\.startedAt/);
  assert.match(js, /overlayState\.detail/);
  assert.match(js, /ui\.boardOverlayDetail\.classList\.toggle\([\s\S]*?is-rematch-waiting[\s\S]*?startsWith\('等待房主再来'\)[\s\S]*?startsWith\('等待挑战者确认再来'\)/);
  assert.match(js, /function maybeSpeakRematchConfirmationPrompt\(/);
  assert.match(js, /function getFinishedMatchOverlayCopy\(/);
  assert.match(js, /赢得押金/);
  assert.match(js, /押金已退回/);
  assert.match(js, /遗憾落败/);
  assert.match(js, /红方胜/);
  assert.match(js, /黑方胜/);
  assert.match(js, /if \(matchStatus === 'FINISHED'\)/);
  assert.match(js, /showFinishedActions:\s*true/);
  assert.match(js, /等待房主再来\(\$\{getRematchCountdownSeconds\(\)\}s\)/);
  assert.match(js, /确认再来\(\$\{getRematchCountdownSeconds\(\)\}s\)/);
  assert.match(js, /等待挑战者确认再来\(\$\{getRematchCountdownSeconds\(\)\}s\)/);
  assert.match(js, /再来一局\(\$\{getRematchCountdownSeconds\(\)\}s\)/);
  assert.match(js, /确认再来/);
  assert.match(js, /async function maybeExpireRematchRequest\(/);
  assert.match(js, /\/api\/xiangqi\/rooms\/\$\{encodeURIComponent\(state\.room\.roomCode\)\}\/rematch\/expire/);
  assert.match(js, /function shouldFlipBoardPerspective\(/);
  assert.match(js, /function syncCountdownStateFromMatch\(/);
  assert.match(js, /function getDisplayedCountdownState\(/);
  assert.match(js, /function startCountdownLoop\(/);
  assert.match(js, /state\.countdown = \{/);
  assert.match(js, /anchorAt:\s*Date\.now\(\)/);
  assert.match(js, /graceMs:\s*previousPhaseKey && previousPhaseKey !== nextPhaseKey \? 900 : 0/);
  assert.match(js, /const previousPhaseKey = state\.countdown\.matchId[\s\S]*?\$\{state\.countdown\.matchId\}:\$\{state\.countdown\.status\}:\$\{state\.countdown\.turnSide\}[\s\S]*?: '';/);
  assert.match(js, /const nextPhaseKey = `\$\{Number\(state\.match\.id \|\| 0\)\}:\$\{String\(state\.match\.status \|\| ''\)\.toUpperCase\(\)\}:\$\{String\(state\.match\.turnSide \|\| ''\)\.toUpperCase\(\)\}`;/);
  assert.match(js, /const elapsedMs = Math\.max\(0,\s*Date\.now\(\) - state\.countdown\.anchorAt - graceMs\);/);
  assert.doesNotMatch(js, /state\.match\.redTimeLeftMs = Math\.max\(0, Number\(state\.match\.redTimeLeftMs \|\| 0\) - 1000\)/);
  assert.doesNotMatch(js, /state\.match\.blackTimeLeftMs = Math\.max\(0, Number\(state\.match\.blackTimeLeftMs \|\| 0\) - 1000\)/);
  assert.match(js, /const shouldFlip = shouldFlipBoardPerspective\(\);/);
  assert.match(js, /const boardFile = shouldFlip \? 8 - file : file;/);
  assert.match(js, /const boardRank = shouldFlip \? 9 - rank : rank;/);
  assert.match(js, /const actualFile = shouldFlip \? 8 - file : file;/);
  assert.match(js, /const actualRank = shouldFlip \? 9 - rank : rank;/);
  assert.match(js, /function getFriendlyXiangqiErrorMessage\(/);
  assert.match(js, /if \(code === 'INSUFFICIENT_BALANCE'\) \{\s*return context === 'create_room' \? '余额不足，无法创建房间。' : '余额不足，无法加入房间。';\s*\}/);
  assert.match(js, /if \(code === 'ROOM_NOT_FOUND'\) \{\s*return '房间号不存在';\s*\}/);
  assert.match(js, /if \(code === 'ILLEGAL_MOVE'\) \{\s*return '不能这么移动';\s*\}/);
  assert.match(js, /function showCreateRoomInsufficientBalanceAlert\(/);
  assert.match(js, /window\.alert\('余额不足，无法创建房间。'\)/);
  assert.match(js, /function showJoinRoomAlert\(/);
  assert.match(js, /window\.alert\(message\);/);
  assert.match(js, /else if \(state\.room\) \{\s*setStatus\('等待对手加入'\);\s*\}/);
  assert.match(js, /function applyShellMode\(/);
  assert.match(js, /classList\.toggle\('is-room-mode'/);
  assert.match(js, /state\.session = loadCachedNexaSession\(\);/);
  assert.match(js, /const cachedUser = loadCachedUser\(\);/);
  assert.match(js, /if \(!isNexaAppEnvironment\(\) && isLocalDevelopmentHost\(\) && cachedUser\?\.userId\) \{/);
  assert.match(js, /await refreshWallet\(\);/);
  assert.match(js, /\/api\/xiangqi\/rooms\/active\?userId=/);
  assert.match(js, /if \(state\.room\) \{\s*return buildPreviewPieces\(\);/);
  assert.doesNotMatch(js, /function renderActiveRoomCard\(/);
  assert.match(js, /async function startReadyMatch\(/);
  assert.match(js, /async function startRematch\(/);
  assert.match(js, /async function confirmRematch\(/);
  assert.match(js, /\/api\/xiangqi\/rooms\/\$\{encodeURIComponent\(state\.room\.roomCode\)\}\/start/);
  assert.match(js, /\/api\/xiangqi\/rooms\/\$\{encodeURIComponent\(state\.room\.roomCode\)\}\/rematch\/request/);
  assert.match(js, /\/api\/xiangqi\/rooms\/\$\{encodeURIComponent\(state\.room\.roomCode\)\}\/rematch\/confirm/);
  assert.match(js, /等待房主开始/);
  assert.match(js, /await postJson\(`\/api\/xiangqi\/matches\/\$\{state\.match\.id\}\/move`, \{/);
  assert.match(js, /setStatus\(getFriendlyXiangqiErrorMessage\(error, 'move'\)\);/);
  assert.match(js, /if \(response\.match\) \{\s*state\.match = response\.match;\s*renderMatch\(\);\s*\}/);
  assert.match(js, /playMoveSound\(\);\s*speakXiangqiCue\(response\.audioCue\);[\s\S]*?if \(response\.status === 'finished'\)/);
  assert.match(js, /if \(response\.status === 'finished'\) \{[\s\S]*?speakFinishedMatchResult\(response\.match\);[\s\S]*?await refreshWallet\(\);/);
  assert.match(js, /else if \(!response\.match\) \{\s*await refreshMatch\(state\.match\.id\);\s*\}/);
  assert.match(js, /unlockMoveSound\(\)\.catch\(\(\) => \{\}\);/);
  assert.match(js, /if \(payload\.actorUserId !== Number\(state\.user\?\.userId \|\| 0\)\) \{[\s\S]*?playMoveSound\(\);[\s\S]*?if \(payload\.audioCue\) \{[\s\S]*?speakXiangqiCue\(payload\.audioCue\);[\s\S]*?\}[\s\S]*?\}/);
  assert.doesNotMatch(js, /ui\.actionDrawBtn\.textContent = hasIncomingDrawOffer \? '同意求和' : '求和';/);
  assert.doesNotMatch(js, /actionDrawRejectBtn/);
  assert.match(js, /if \(response\?\.match\) \{\s*state\.match = response\.match;\s*renderMatch\(\);\s*\} else \{\s*await refreshMatch\(state\.match\.id\);\s*\}/);
  assert.match(js, /source\.addEventListener\('match\.finished',[\s\S]*?speakFinishedMatchResult\(payload\.match\);/);
  assert.match(js, /source\.addEventListener\('room\.updated',[\s\S]*?maybeSpeakRematchConfirmationPrompt\(\);/);
  assert.match(js, /source\.addEventListener\('match\.draw-offer',[\s\S]*?openDrawConfirmModal\(\);/);
  assert.match(js, /function bindActions\(/);
  assert.match(js, /ui\.startMatchBtn\?\.addEventListener\('click', \(\) => startReadyMatch\(\)\.catch/);
  assert.match(js, /ui\.confirmRematchBtn\?\.addEventListener\('click', \(\) => confirmRematch\(\)\.catch/);
  assert.match(js, /ui\.rematchBtn\?\.addEventListener\('click', \(\) => startRematch\(\)\.catch/);
  assert.match(js, /ui\.returnLobbyBtn\?\.addEventListener\('click', \(\) => returnToLobby\(\)\.catch/);
  assert.match(js, /ui\.joinRoomCode\?\.addEventListener\('input', \(\) => \{/);
  assert.match(js, /replace\(\/\\D\+\/g, ''\)\.slice\(0, 6\)/);
  assert.match(js, /ui\.joinRoomClearBtn\?\.addEventListener\('click', \(\) => \{/);
  assert.match(js, /document\.addEventListener\(eventName,\s*\(\) => \{\s*unlockMoveSound\(\)\.catch\(\(\) => \{\}\);\s*\},\s*\{ once: true, passive: true \}\);/);
  assert.match(js, /ui\.createRoomBtn\?\.addEventListener\('click', \(\) => createRoom\(\)\.catch\(\(error\) => \{[\s\S]*?const message = getFriendlyXiangqiErrorMessage\(error, 'create_room'\);[\s\S]*?showCreateRoomInsufficientBalanceAlert\(message\);[\s\S]*?setStatus\(message\);[\s\S]*?\}\)\);/);
  assert.match(js, /ui\.joinRoomBtn\?\.addEventListener\('click', \(\) => joinRoom\(\)\.catch\(\(error\) => \{[\s\S]*?const message = getFriendlyXiangqiErrorMessage\(error, 'join_room'\);[\s\S]*?showJoinRoomAlert\(message\);[\s\S]*?setStatus\(message\);[\s\S]*?\}\)\);/);
  assert.doesNotMatch(js, /ui\.actionDrawRejectBtn\?\.addEventListener\('click', async \(\) => \{/);
  assert.match(js, /ui\.drawConfirmAcceptBtn\?\.addEventListener\('click', async \(\) => \{/);
  assert.match(js, /ui\.drawConfirmAcceptBtn\?\.addEventListener\('click', async \(\) => \{[\s\S]*?if \(response\?\.match\) \{[\s\S]*?state\.match = response\.match;[\s\S]*?renderMatch\(\);[\s\S]*?if \(String\(response\.status \|\| ''\)\.toLowerCase\(\) === 'finished'\) \{[\s\S]*?speakFinishedMatchResult\(response\.match\);[\s\S]*?await refreshWallet\(\);[\s\S]*?\}[\s\S]*?\} else \{[\s\S]*?await refreshMatch\(state\.match\.id\);[\s\S]*?\}/);
  assert.match(js, /ui\.drawConfirmRejectBtn\?\.addEventListener\('click', async \(\) => \{/);
  assert.match(js, /await requestAmount\('输入要充值到游戏账户的 USDT 金额'\)/);
  assert.match(js, /await requestAmount\('输入要提现回 Nexa 的 USDT 金额'\)/);
  assert.match(js, /setStatus\('请在 Nexa 内提现吗。'\);/);
  assert.match(js, /timePresetButtons: Array\.from\(document\.querySelectorAll\('\[data-time-preset\]'\)\)/);
  assert.match(js, /syncRoomUrl\(null\);[\s\S]*?await refreshWallet\(\);[\s\S]*?renderMatch\(\);/);
});

test('xiangqi css delivers a distinctive mobile-first room layout', () => {
  const css = fs.readFileSync(cssPath, 'utf8');

  assert.match(css, /--xiangqi-page-bg:\s*#f6f5f3;/);
  assert.match(css, /\.xiangqi-shell\s*\{[\s\S]*?display:\s*grid;/);
  assert.match(css, /\.xiangqi-room-grid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(css, /\.xiangqi-board\s*\{[\s\S]*?aspect-ratio:\s*9 \/ 10;/);
  assert.match(css, /\.xiangqi-board\s*\{[\s\S]*?overflow:\s*hidden;/);
  assert.match(css, /\.xiangqi-board-stage\s*\{[\s\S]*?position:\s*relative;/);
  assert.match(css, /\.xiangqi-board-overlay\s*\{/);
  assert.match(css, /\.xiangqi-board-overlay__message\s*\{/);
  assert.match(css, /\.xiangqi-board-overlay__detail\s*\{/);
  assert.match(css, /\.xiangqi-board-overlay__detail\.is-rematch-waiting\s*\{[\s\S]*?background:\s*linear-gradient\(180deg,\s*#d93c33 0%,\s*#b91f18 100%\);[\s\S]*?color:\s*#fff;[\s\S]*?font-size:\s*19px;[\s\S]*?font-weight:\s*900;/);
  assert.match(css, /\.xiangqi-board-overlay__start\s*\{/);
  assert.match(css, /\.xiangqi-board-overlay__actions\s*\{/);
  assert.match(css, /\.xiangqi-player-card--footer\s*\{/);
  assert.match(css, /\.xiangqi-board-foot\s*\{/);
  assert.match(css, /\.xiangqi-board-foot > \* \s*\{[\s\S]*?min-height:\s*122px;/);
  assert.match(css, /\.xiangqi-board-status-pill\s*\{/);
  assert.match(css, /\.xiangqi-board-foot \.xiangqi-player-card--footer\s*\{[\s\S]*?margin-top:\s*0;/);
  assert.match(css, /\.xiangqi-player-card--red\s*\{/);
  assert.match(css, /\.xiangqi-player-card--black\s*\{/);
  assert.match(css, /\.xiangqi-player-card p\s*\{[\s\S]*?color:\s*#c62828;[\s\S]*?font-weight:\s*900;/);
  assert.match(css, /\.xiangqi-board-head\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0,\s*0\.9fr\)\s+minmax\(0,\s*1\.1fr\);/);
  assert.match(css, /#xiangqiRoomBadge\s*\{[\s\S]*?font-size:\s*14px;[\s\S]*?color:\s*var\(--xiangqi-muted\);/);
  assert.match(css, /#xiangqiRoomBadge\s+\.xiangqi-room-badge__value\s*\{[\s\S]*?font-size:\s*34px;[\s\S]*?font-weight:\s*900;[\s\S]*?color:\s*#1f5cff;/);
  assert.match(css, /#xiangqiMatchStake\s*\{[\s\S]*?margin-top:\s*8px;/);
  assert.match(css, /\.xiangqi-board__svg-wrap,\s*[\s\S]*?\.xiangqi-board__hit-area\s*\{/);
  assert.match(css, /\.xiangqi-board__grid-lines line,\s*[\s\S]*?\.xiangqi-board__palace-lines line\s*\{/);
  assert.match(css, /\.xiangqi-board__river-text text\s*\{/);
  assert.doesNotMatch(css, /\.xiangqi-board__coord\s*\{/);
  assert.match(css, /\.xiangqi-action-bar\s*\{[\s\S]*?grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(css, /\.xiangqi-wallet-card__side\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,\s*minmax\(74px,\s*1fr\)\);[\s\S]*?grid-template-rows:\s*repeat\(2,\s*minmax\(44px,\s*auto\)\);/);
  assert.match(css, /\.xiangqi-wallet-card__actions\s*\{[\s\S]*?display:\s*contents;/);
  assert.match(css, /\.xiangqi-wallet-card__chips span\s*\{[\s\S]*?background:\s*transparent;[\s\S]*?color:\s*#fff;/);
  assert.match(css, /\.xiangqi-wallet-card__amount strong\s*\{[\s\S]*?font-size:\s*clamp\(20px,\s*3\.5vw,\s*28px\);/);
  assert.match(css, /\.xiangqi-wallet-action\s*\{/);
  assert.match(css, /#xiangqiDepositBtn\s*\{[\s\S]*?grid-column:\s*1;[\s\S]*?grid-row:\s*1;/);
  assert.match(css, /#xiangqiWithdrawBtn\s*\{[\s\S]*?grid-column:\s*2;[\s\S]*?grid-row:\s*1;/);
  assert.match(css, /\.xiangqi-wallet-action--ledger\s*\{[\s\S]*?grid-column:\s*2;[\s\S]*?grid-row:\s*2;/);
  assert.match(css, /\.xiangqi-amount-modal\s*\{/);
  assert.match(css, /\.xiangqi-amount-sheet\s*\{/);
  assert.match(css, /\.xiangqi-amount-input\s*\{/);
  assert.match(css, /\.xiangqi-room-input,\s*[\s\S]*?box-shadow:\s*inset 0 0 0 1px rgba\(15,\s*152,\s*113,\s*0\.42\);/);
  assert.match(css, /\.xiangqi-room-input-wrap\s*\{\s*position:\s*relative;/);
  assert.match(css, /\.xiangqi-room-input\s*\{[\s\S]*?background:\s*#f7f7f7;[\s\S]*?box-shadow:\s*inset 0 0 0 1px rgba\(15,\s*152,\s*113,\s*0\.42\);[\s\S]*?padding:\s*0 54px 0 18px;/);
  assert.match(css, /\.xiangqi-room-input-clear\s*\{[\s\S]*?position:\s*absolute;[\s\S]*?right:\s*14px;/);
  assert.match(css, /\.xiangqi-room-input-clear\[hidden\]\s*\{\s*display:\s*none;/);
  assert.match(css, /\.xiangqi-room-summary\s*\{[\s\S]*?background:\s*#fff;[\s\S]*?box-shadow:\s*none;/);
  assert.match(css, /\.xiangqi-create-options\s*\{/);
  assert.match(css, /\.xiangqi-option-group\s*\{/);
  assert.match(css, /\.xiangqi-time-preset\s*\{/);
  assert.doesNotMatch(css, /\.xiangqi-active-room-card\s*\{/);
  assert.match(css, /\.xiangqi-board-wrap\s*\{[\s\S]*?display:\s*none;/);
  assert.match(css, /\.xiangqi-shell\.is-room-mode\s+\.xiangqi-wallet-card,\s*[\s\S]*?display:\s*none;/);
  assert.match(css, /\.xiangqi-shell\.is-room-mode\s+\.xiangqi-room-grid\s*\{[\s\S]*?display:\s*none;/);
  assert.match(css, /\.xiangqi-shell\.is-room-mode\s+\.xiangqi-board-wrap\s*\{[\s\S]*?display:\s*block;/);
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.xiangqi-shell\s*\{[\s\S]*?padding:\s*20px 14px 30px;/);
  assert.match(css, /@media \(max-width: 720px\)[\s\S]*?\.xiangqi-room-cta\s*\{[\s\S]*?min-height:\s*64px;/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?\.xiangqi-shell\s*\{[\s\S]*?padding:\s*12px 6px 20px;/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?width:\s*calc\(100% - 12px\);/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?\.xiangqi-wallet-card__amount strong\s*\{[\s\S]*?font-size:\s*18px;/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?\.xiangqi-wallet-card__side\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,\s*minmax\(62px,\s*1fr\)\);[\s\S]*?grid-template-rows:\s*repeat\(2,\s*minmax\(38px,\s*auto\)\);/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?\.xiangqi-room-grid\s*\{[\s\S]*?gap:\s*12px;/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?\.xiangqi-room-card\s*\{[\s\S]*?padding:\s*16px;/);
  assert.match(css, /@media \(max-width: 430px\)[\s\S]*?\.xiangqi-danger-btn,\s*[\s\S]*?font-size:\s*14px;/);
});
